
export const countryName = [
    "Please Select", "Albania", "Algeria", "American Samoa", "Andorra",
    "Angola", "Anguilla", "Antarctica", "Argentina",
    "Aruba", "Australia", "Austria", "Bahamas The",
    "Barbados", "Belgium", "Bermuda", "Bhutan", "Bouvet Island",
    "Brazil", "British Indian Ocean Territory", "Brunei", "Bulgaria",
    "Burundi", "Cambodia", "Canada", "Cape Verde", "Cayman Islands",
    "Chad", "Chile", "China", "Christmas Island", "Cocos (Keeling) Islands",
    "Colombia", "Comoros", "Cook Islands", "Costa Rica", "Croatia (Hrvatska)",
    "Cyprus", "Czech Republic", "Denmark", "Djibouti", "East Timor", "Ecuador",
    "Equatorial Guinea", "Eritrea", "External Territories of Australia", "Falkland Islands",
    "Faroe Islands", "Fiji Islands", "Finland", "France", "French Guiana", "French Polynesia",
    "French Southern Territories", "Gambia The", "Georgia", "Germany", "Gibraltar", "Greece", "Greenland",
    "Grenada", "Guadeloupe", "Guam", "Guernsey and Alderney", "Guinea", "Guyana", "Heard and McDonald Islands",
    "Honduras", "Hong Kong S.A.R.", "Hungary", "Iceland", "India", "Ireland", "Israel", "Italy", "Jamaica", "Japan",
    "Jersey", "Jordan", "Kazakhstan", "Korea North", "Korea South", "Lesotho", "Liechtenstein", "Lithuania", "Luxembourg",
    "Macau S.A.R.", "Madagascar", "Maldives", "Man (Isle of)", "Martinique", "Mauritania", "Mauritius", "Mayotte", "Mexico",
    "Micronesia", "Monaco", "Montserrat", "Morocco", "Myanmar", "Nauru", "Netherlands Antilles", "Netherlands The", "New Caledonia",
    "New Zealand", "Niue", "Norfolk Island", "Northern Mariana Islands", "Norway", "Palau", "Palestinian Territory Occupied", "Papua new Guinea",
    "Peru", "Philippines", "Pitcairn Island", "Poland", "Portugal", "Puerto Rico", "Qatar", "Reunion", "Romania", "Russia", "Rwanda", "Saint Helena", "Saint Kitts And Nevis",
    "Saint Lucia", "Saint Pierre and Miquelon", "Saint Vincent And The Grenadines", "San Marino", "Singapore", "Slovakia", "Slovenia", "Smaller Territories of the UK", "South Africa", "South Georgia",
    "Spain", "Svalbard And Jan Mayen Islands", "Swaziland", "Sweden", "Switzerland", "Taiwan", "Thailand", "Togo", "Tokelau", "Trinidad And Tobago", "Tunisia", "Turkmenistan", "Turks And Caicos Islands",
    "Tuvalu", "United Arab Emirates", "United Kingdom", "United States", "United States Minor Outlying Islands", "Uruguay", "Uzbekistan", "Vatican City State (Holy See)", "Virgin Islands (British)", "Virgin Islands (US)", "Wallis And Futuna Islands", "Western Sahara", "Yugoslavia"
]

export const nameCountries = [
    { 'country': 'Afghanistan', 'code': 'AF' },
    { 'country': 'Aland Islands', 'code': 'AX' },
    { 'country': 'Albania', 'code': 'AL' },
    { 'country': 'Algeria', 'code': 'DZ' },
    { 'country': 'American Samoa', 'code': 'AS' },
    { 'country': 'Andorra', 'code': 'AD' },
    { 'country': 'Angola', 'code': 'AO' },
    { 'country': 'Anguilla', 'code': 'AI' },
    { 'country': 'Antarctica', 'code': 'AQ' },
    { 'country': 'Antigua And Barbuda', 'code': 'AG' },
    { 'country': 'Argentina', 'code': 'AR' },
    { 'country': 'Armenia', 'code': 'AM' },
    { 'country': 'Aruba', 'code': 'AW' },
    { 'country': 'Australia', 'code': 'AU' },
    { 'country': 'Austria', 'code': 'AT' },
    { 'country': 'Azerbaijan', 'code': 'AZ' },
    { 'country': 'Bahamas', 'code': 'BS' },
    { 'country': 'Bahrain', 'code': 'BH' },
    { 'country': 'Bangladesh', 'code': 'BD' },
    { 'country': 'Barbados', 'code': 'BB' },
    { 'country': 'Belarus', 'code': 'BY' },
    { 'country': 'Belgium', 'code': 'BE' },
    { 'country': 'Belize', 'code': 'BZ' },
    { 'country': 'Benin', 'code': 'BJ' },
    { 'country': 'Bermuda', 'code': 'BM' },
    { 'country': 'Bhutan', 'code': 'BT' },
    { 'country': 'Bolivia', 'code': 'BO' },
    { 'country': 'Bosnia And Herzegovina', 'code': 'BA' },
    { 'country': 'Botswana', 'code': 'BW' },
    { 'country': 'Bouvet Island', 'code': 'BV' },
    { 'country': 'Brazil', 'code': 'BR' },
    { 'country': 'British Indian Ocean Territory', 'code': 'IO' },
    { 'country': 'Brunei Darussalam', 'code': 'BN' },
    { 'country': 'Bulgaria', 'code': 'BG' },
    { 'country': 'Burkina Faso', 'code': 'BF' },
    { 'country': 'Burundi', 'code': 'BI' },
    { 'country': 'Cambodia', 'code': 'KH' },
    { 'country': 'Cameroon', 'code': 'CM' },
    { 'country': 'Canada', 'code': 'CA' },
    { 'country': 'Cape Verde', 'code': 'CV' },
    { 'country': 'Cayman Islands', 'code': 'KY' },
    { 'country': 'Central African Republic', 'code': 'CF' },
    { 'country': 'Chad', 'code': 'TD' },
    { 'country': 'Chile', 'code': 'CL' },
    { 'country': 'China', 'code': 'CN' },
    { 'country': 'Christmas Island', 'code': 'CX' },
    { 'country': 'Cocos (Keeling) Islands', 'code': 'CC' },
    { 'country': 'Colombia', 'code': 'CO' },
    { 'country': 'Comoros', 'code': 'KM' },
    { 'country': 'Congo', 'code': 'CG' },
    { 'country': 'Congo, Democratic Republic', 'code': 'CD' },
    { 'country': 'Cook Islands', 'code': 'CK' },
    { 'country': 'Costa Rica', 'code': 'CR' },
    { 'country': 'Cote D\'Ivoire', 'code': 'CI' },
    { 'country': 'Croatia', 'code': 'HR' },
    { 'country': 'Cuba', 'code': 'CU' },
    { 'country': 'Cyprus', 'code': 'CY' },
    { 'country': 'Czech Republic', 'code': 'CZ' },
    { 'country': 'Denmark', 'code': 'DK' },
    { 'country': 'Djibouti', 'code': 'DJ' },
    { 'country': 'Dominica', 'code': 'DM' },
    { 'country': 'Dominican Republic', 'code': 'DO' },
    { 'country': 'Ecuador', 'code': 'EC' },
    { 'country': 'Egypt', 'code': 'EG' },
    { 'country': 'El Salvador', 'code': 'SV' },
    { 'country': 'Equatorial Guinea', 'code': 'GQ' },
    { 'country': 'Eritrea', 'code': 'ER' },
    { 'country': 'Estonia', 'code': 'EE' },
    { 'country': 'Ethiopia', 'code': 'ET' },
    { 'country': 'Falkland Islands (Malvinas)', 'code': 'FK' },
    { 'country': 'Faroe Islands', 'code': 'FO' },
    { 'country': 'Fiji', 'code': 'FJ' },
    { 'country': 'Finland', 'code': 'FI' },
    { 'country': 'France', 'code': 'FR' },
    { 'country': 'French Guiana', 'code': 'GF' },
    { 'country': 'French Polynesia', 'code': 'PF' },
    { 'country': 'French Southern Territories', 'code': 'TF' },
    { 'country': 'Gabon', 'code': 'GA' },
    { 'country': 'Gambia', 'code': 'GM' },
    { 'country': 'Georgia', 'code': 'GE' },
    { 'country': 'Germany', 'code': 'DE' },
    { 'country': 'Ghana', 'code': 'GH' },
    { 'country': 'Gibraltar', 'code': 'GI' },
    { 'country': 'Greece', 'code': 'GR' },
    { 'country': 'Greenland', 'code': 'GL' },
    { 'country': 'Grenada', 'code': 'GD' },
    { 'country': 'Guadeloupe', 'code': 'GP' },
    { 'country': 'Guam', 'code': 'GU' },
    { 'country': 'Guatemala', 'code': 'GT' },
    { 'country': 'Guernsey', 'code': 'GG' },
    { 'country': 'Guinea', 'code': 'GN' },
    { 'country': 'Guinea-Bissau', 'code': 'GW' },
    { 'country': 'Guyana', 'code': 'GY' },
    { 'country': 'Haiti', 'code': 'HT' },
    { 'country': 'Heard Island & Mcdonald Islands', 'code': 'HM' },
    { 'country': 'Holy See (Vatican City State)', 'code': 'VA' },
    { 'country': 'Honduras', 'code': 'HN' },
    { 'country': 'Hong Kong', 'code': 'HK' },
    { 'country': 'Hungary', 'code': 'HU' },
    { 'country': 'Iceland', 'code': 'IS' },
    { 'country': 'India', 'code': 'IN' },
    { 'country': 'Indonesia', 'code': 'ID' },
    { 'country': 'Iran, Islamic Republic Of', 'code': 'IR' },
    { 'country': 'Iraq', 'code': 'IQ' },
    { 'country': 'Ireland', 'code': 'IE' },
    { 'country': 'Isle Of Man', 'code': 'IM' },
    { 'country': 'Israel', 'code': 'IL' },
    { 'country': 'Italy', 'code': 'IT' },
    { 'country': 'Jamaica', 'code': 'JM' },
    { 'country': 'Japan', 'code': 'JP' },
    { 'country': 'Jersey', 'code': 'JE' },
    { 'country': 'Jordan', 'code': 'JO' },
    { 'country': 'Kazakhstan', 'code': 'KZ' },
    { 'country': 'Kenya', 'code': 'KE' },
    { 'country': 'Kiribati', 'code': 'KI' },
    { 'country': 'Korea', 'code': 'KR' },
    { 'country': 'Kuwait', 'code': 'KW' },
    { 'country': 'Kyrgyzstan', 'code': 'KG' },
    { 'country': 'Lao People\'s Democratic Republic', 'code': 'LA' },
    { 'country': 'Latvia', 'code': 'LV' },
    { 'country': 'Lebanon', 'code': 'LB' },
    { 'country': 'Lesotho', 'code': 'LS' },
    { 'country': 'Liberia', 'code': 'LR' },
    { 'country': 'Libyan Arab Jamahiriya', 'code': 'LY' },
    { 'country': 'Liechtenstein', 'code': 'LI' },
    { 'country': 'Lithuania', 'code': 'LT' },
    { 'country': 'Luxembourg', 'code': 'LU' },
    { 'country': 'Macao', 'code': 'MO' },
    { 'country': 'Macedonia', 'code': 'MK' },
    { 'country': 'Madagascar', 'code': 'MG' },
    { 'country': 'Malawi', 'code': 'MW' },
    { 'country': 'Malaysia', 'code': 'MY' },
    { 'country': 'Maldives', 'code': 'MV' },
    { 'country': 'Mali', 'code': 'ML' },
    { 'country': 'Malta', 'code': 'MT' },
    { 'country': 'Marshall Islands', 'code': 'MH' },
    { 'country': 'Martinique', 'code': 'MQ' },
    { 'country': 'Mauritania', 'code': 'MR' },
    { 'country': 'Mauritius', 'code': 'MU' },
    { 'country': 'Mayotte', 'code': 'YT' },
    { 'country': 'Mexico', 'code': 'MX' },
    { 'country': 'Micronesia, Federated States Of', 'code': 'FM' },
    { 'country': 'Moldova', 'code': 'MD' },
    { 'country': 'Monaco', 'code': 'MC' },
    { 'country': 'Mongolia', 'code': 'MN' },
    { 'country': 'Montenegro', 'code': 'ME' },
    { 'country': 'Montserrat', 'code': 'MS' },
    { 'country': 'Morocco', 'code': 'MA' },
    { 'country': 'Mozambique', 'code': 'MZ' },
    { 'country': 'Myanmar', 'code': 'MM' },
    { 'country': 'Namibia', 'code': 'NA' },
    { 'country': 'Nauru', 'code': 'NR' },
    { 'country': 'Nepal', 'code': 'NP' },
    { 'country': 'Netherlands', 'code': 'NL' },
    { 'country': 'Netherlands Antilles', 'code': 'AN' },
    { 'country': 'New Caledonia', 'code': 'NC' },
    { 'country': 'New Zealand', 'code': 'NZ' },
    { 'country': 'Nicaragua', 'code': 'NI' },
    { 'country': 'Niger', 'code': 'NE' },
    { 'country': 'Nigeria', 'code': 'NG' },
    { 'country': 'Niue', 'code': 'NU' },
    { 'country': 'Norfolk Island', 'code': 'NF' },
    { 'country': 'Northern Mariana Islands', 'code': 'MP' },
    { 'country': 'Norway', 'code': 'NO' },
    { 'country': 'Oman', 'code': 'OM' },
    { 'country': 'Pakistan', 'code': 'PK' },
    { 'country': 'Palau', 'code': 'PW' },
    { 'country': 'Palestinian Territory, Occupied', 'code': 'PS' },
    { 'country': 'Panama', 'code': 'PA' },
    { 'country': 'Papua New Guinea', 'code': 'PG' },
    { 'country': 'Paraguay', 'code': 'PY' },
    { 'country': 'Peru', 'code': 'PE' },
    { 'country': 'Philippines', 'code': 'PH' },
    { 'country': 'Pitcairn', 'code': 'PN' },
    { 'country': 'Poland', 'code': 'PL' },
    { 'country': 'Portugal', 'code': 'PT' },
    { 'country': 'Puerto Rico', 'code': 'PR' },
    { 'country': 'Qatar', 'code': 'QA' },
    { 'country': 'Reunion', 'code': 'RE' },
    { 'country': 'Romania', 'code': 'RO' },
    { 'country': 'Russian Federation', 'code': 'RU' },
    { 'country': 'Rwanda', 'code': 'RW' },
    { 'country': 'Saint Barthelemy', 'code': 'BL' },
    { 'country': 'Saint Helena', 'code': 'SH' },
    { 'country': 'Saint Kitts And Nevis', 'code': 'KN' },
    { 'country': 'Saint Lucia', 'code': 'LC' },
    { 'country': 'Saint Martin', 'code': 'MF' },
    { 'country': 'Saint Pierre And Miquelon', 'code': 'PM' },
    { 'country': 'Saint Vincent And Grenadines', 'code': 'VC' },
    { 'country': 'Samoa', 'code': 'WS' },
    { 'country': 'San Marino', 'code': 'SM' },
    { 'country': 'Sao Tome And Principe', 'code': 'ST' },
    { 'country': 'Saudi Arabia', 'code': 'SA' },
    { 'country': 'Senegal', 'code': 'SN' },
    { 'country': 'Serbia', 'code': 'RS' },
    { 'country': 'Seychelles', 'code': 'SC' },
    { 'country': 'Sierra Leone', 'code': 'SL' },
    { 'country': 'Singapore', 'code': 'SG' },
    { 'country': 'Slovakia', 'code': 'SK' },
    { 'country': 'Slovenia', 'code': 'SI' },
    { 'country': 'Solomon Islands', 'code': 'SB' },
    { 'country': 'Somalia', 'code': 'SO' },
    { 'country': 'South Africa', 'code': 'ZA' },
    { 'country': 'South Georgia And Sandwich Isl.', 'code': 'GS' },
    { 'country': 'Spain', 'code': 'ES' },
    { 'country': 'Sri Lanka', 'code': 'LK' },
    { 'country': 'Sudan', 'code': 'SD' },
    { 'country': 'Suriname', 'code': 'SR' },
    { 'country': 'Svalbard And Jan Mayen', 'code': 'SJ' },
    { 'country': 'Swaziland', 'code': 'SZ' },
    { 'country': 'Sweden', 'code': 'SE' },
    { 'country': 'Switzerland', 'code': 'CH' },
    { 'country': 'Syrian Arab Republic', 'code': 'SY' },
    { 'country': 'Taiwan', 'code': 'TW' },
    { 'country': 'Tajikistan', 'code': 'TJ' },
    { 'country': 'Tanzania', 'code': 'TZ' },
    { 'country': 'Thailand', 'code': 'TH' },
    { 'country': 'Timor-Leste', 'code': 'TL' },
    { 'country': 'Togo', 'code': 'TG' },
    { 'country': 'Tokelau', 'code': 'TK' },
    { 'country': 'Tonga', 'code': 'TO' },
    { 'country': 'Trinidad And Tobago', 'code': 'TT' },
    { 'country': 'Tunisia', 'code': 'TN' },
    { 'country': 'Turkey', 'code': 'TR' },
    { 'country': 'Turkmenistan', 'code': 'TM' },
    { 'country': 'Turks And Caicos Islands', 'code': 'TC' },
    { 'country': 'Tuvalu', 'code': 'TV' },
    { 'country': 'Uganda', 'code': 'UG' },
    { 'country': 'Ukraine', 'code': 'UA' },
    { 'country': 'United Arab Emirates', 'code': 'AE' },
    { 'country': 'United Kingdom', 'code': 'GB' },
    { 'country': 'United States', 'code': 'US' },
    { 'country': 'United States Outlying Islands', 'code': 'UM' },
    { 'country': 'Uruguay', 'code': 'UY' },
    { 'country': 'Uzbekistan', 'code': 'UZ' },
    { 'country': 'Vanuatu', 'code': 'VU' },
    { 'country': 'Venezuela', 'code': 'VE' },
    { 'country': 'Viet Nam', 'code': 'VN' },
    { 'country': 'Virgin Islands, British', 'code': 'VG' },
    { 'country': 'Virgin Islands, U.S.', 'code': 'VI' },
    { 'country': 'Wallis And Futuna', 'code': 'WF' },
    { 'country': 'Western Sahara', 'code': 'EH' },
    { 'country': 'Yemen', 'code': 'YE' },
    { 'country': 'Zambia', 'code': 'ZM' },
    { 'country': 'Zimbabwe', 'code': 'ZW' }
]


export const provinceName = [
    "indonesia", "Algeria", "Alger", "Tehran"
]

export const IDType = [
    "Driver License", "Passport", "Local ID"
]

// export const IDType = [
//     "D", "P", "L"
// ]

export const AccountType = [
    "Checking", "Saving"
]