export default Object.freeze({
    SUBMIT_FORM: "SUBMIT_FORM",
    SUBMIT_FORM2: "SUBMIT_FORM2",
    STEPPER_INDEX: "STEPPER_INDEX",
    FORM_TYPE: "FORM_TYPE",
    LLC_BENEFICIARY_VALIDATE: "LLC_BENEFICIARY_VALIDATE"
});
